Asqwklop12
goodStudy-e/java-racingcar pull request #3
Opened 2020-01-17 02:49 UTC by asqwklop12

요구사항중...
 - 5자리이상은 입력이 되지 않는건 되지 않습니다.
 - 차량이 1대이하가 존재할 경우에도 실행됩니다.
이 두가지 사항은 무시하고 해주세요,ㅜㅜ
감사합니다.

2020-01-27 12:27 UTC, JunHoPark93 requested changes
안녕하세요! 늦어서 죄송합니다..ㅎㅎ
stream 사용과 함께 저번보다 더 좋아지신거같아요!
근데 test 폴더가 없네요.. 혹시 누락된거라면 올려주세요 ㅎㅎ
전체적으로 패키지를 잘게 나누려는 흔적이 보여서 좋습니다!
하지만 도메인로직과 출력 로직을 좀 더 분리한다면 좋을 것 같습니다!
만드신 view 라는 패키지에 출력로직을 (system.out.println) 다 몰아넣고 domain은 정말 순수한 상태만 가지고 있게 끔 변경한다면 더 깔끔해질 것 같아요!
말씀드린 리뷰는 전부 반영하실 필요는 없지만, 방금 위에서 언급드린 도메인 로직을 잘 보존하는건 필요합니다 !

2020-01-27 12:27 UTC, JunHoPark93 commented on src/main/java/view/Racing.java
> +	private final static String INPUTCARS = "자동차를 입력해주세요.(자동차는 `,`로 구분됩니다.)";
상수 선언이 순서가 바뀌었네요. private static final 로 해주세요. INPUTCARS 라고 상수를 빼는 시도는 좋습니다. 하지만 단어마다 _ 언더스코어로 구분해주세요! INPUT_CARS
그리고 변수명이 INPUT_CARS라면 입력된 자동차들에 대한 상수명 같아요.  무슨무슨_MSG 이런식의 네이밍은 어떨가요

2020-01-27 12:27 UTC, JunHoPark93 commented on src/main/java/view/Racing.java
> +	private final static String HOWMANYCOUNT = "몇 번 반복하시겠습니까? ";
위와 같은 내용입니다.

2020-01-27 12:27 UTC, JunHoPark93 commented on src/main/java/view/Racing.java
> +	private Scanner sc = new Scanner(System.in);
상수 선언과 일반 변수선언은 개행으로 구분해주는게 좋습니다. 구글 자바 코딩 가이드를 참고해주세요!

2020-01-27 12:27 UTC, JunHoPark93 commented on src/main/java/model/Setting.java
> +public class Setting {
Setting 이라는 클래스이름이 모호합니다. 내용을 보았을 때 입력된 값들을 파싱해서 반환하는것이기 때문에 
무슨무슨Util 이라든지 무슨무슨Helper 가 더 어울릴 것 같아요. 예를들어 UserInputHelper 라든지요. 이름은 딱 보고 뭐하는지 아는정도면 좋을 것 같습니다

2020-01-27 12:27 UTC, JunHoPark93 commented on src/main/java/model/Setting.java
> +	private String[] splitComma(String str) {
메서드를 잘 분리해주셨네요! 
한가지 아쉬운점은 public 메서드인 regist 라는 것을 보았을 때 private 메서드가 보이네요. 그러면 따라 나오는 private 메서드를 public 메서드 밑에 위치시키는게 위에서 아래로 읽기 좋습니다. splitComma가 제일 마지막에 호출되네요. 그러면 3번째에 위치하는게 좋겠죠?

2020-01-27 12:27 UTC, JunHoPark93 commented on src/main/java/model/Setting.java
> +	public List<Track> regist(String str) {
regist라는 메서드명은 없는단어입니다. register로 변경해주세요! 단어가 이상하면 IntelliJ에서 밑줄로 경고가 표시됩니다 !

2020-01-27 12:27 UTC, JunHoPark93 commented on src/main/java/model/Setting.java
> +				.map(Track :: new)
전체적으로 컨벤션이 맞지 않아 option + cmd + L 을 눌러서 줄 정리를 해주세요! 한 번에 정리됩니다 :)

2020-01-27 12:27 UTC, JunHoPark93 commented on src/main/java/model/Setting.java
> +		return new HashSet<>(Arrays.asList(splitComma(str)));
Set으로 하신 이유가 있을까요?
아마 중복된 자동차의 이름을 거르려고 하신거 같은데 만약에 그렇다면 클라이언트(사용자)쪽에 중복된 입력이라고 메세지를 내려주는게 맞지않을까요? (게임 정책에 따라 달라질 수 있는 부분이지만)
그런게 아니라면 사용자가 동명 자동차를 의도적으로 넣었다면 서버쪽에서 처리가 되지 않는 결과가 나오게 되겠죠.

2020-01-27 12:27 UTC, JunHoPark93 commented on src/main/java/model/Setting.java
> +import java.util.ArrayList;
쓰지 않는 import는 제거해주세요!
option + cmd + L 로 정리할 수 있습니다!

2020-01-27 12:27 UTC, JunHoPark93 commented on src/main/java/view/Racing.java
> +	private void callRepeat(List<Track> inputCars) {
메서드 네이밍을 의도하신거라면 repeatCall이 맞을것 같네요 :)

2020-01-27 12:27 UTC, JunHoPark93 commented on src/main/java/domain/Track.java
> +public class Track {
트랙이라는 도메인을 도출하셨네요. 각 자동차의 레일로 생각하신 것 같아요. 이렇게 볼 수도 있겠네요. 멋진 생각입니다 👍

2020-01-27 12:27 UTC, JunHoPark93 commented on src/main/java/domain/Track.java
> +	public String print() {
만드신 패키지에 view라는 패키지가 있어요. 레이어별로 분리를 잘 하신거같아요. 그런데 domain에는 view레이어에 종속적인 부분이 들어가면 안됩니다. 도메인은 정말 순수한 상태만 가지고 있어야 해요.
만약에 출력 형식이 바뀌는 요구사항이 발생한다면, 그 요구사항을 반영하기 위해 Track이라는 도메인을 수정해야 합니다. Track은 정말 몇 칸이 이동됐는지에 대한 값만 가지고 있고 view에서 그것을 가져다가 그려야 합니다.
이 출력 로직을 view 레이어로 옮겨보는건 어떨까요?

2020-01-27 12:27 UTC, JunHoPark93 commented on src/main/java/domain/Track.java
> +	public void currentPosition() {
메서드명이 currentPosition() 이네요. 마치 현재 위치를 반환하는 메서드명 같습니다.
하지만 메서드 내용을 보면 자동차의 상태(state)를 변화시키고 있습니다. 
메서드는 명령(데이터의 상태를 변경시키는 것) 과 쿼리(데이터를 조회하는 것)를 잘 분리해야 합니다. 
네이밍만 보면 currentPosition은 쿼리에 해당합니다. 하지만 자동차의 상태를 변화시킵니다. 자칫 오해의 소지가 있을 수 있으니 바꿔보는건 어떨까요?

2020-01-27 12:27 UTC, JunHoPark93 commented on src/main/java/controller/Winner.java
> +				.map(track-> track.getCar().getName())
track 에서 name을 가져오고 있습니다. track 의 getCar를 한다는 것은 track이 car를 가지고 있다는 것을 밖에 노출시킵니다. 객체는 캡슐화를 잘 해야 합니다. 즉 밖에서 track을 보았을 때 car의 이름을 가져오는 메서드만 정의해주면, car를 노출시키지 않아도 됩니다.
car를 노출시킴으로써 가지는 단점은 의도치 않게 car 객체를 수정하는 것입니다. 
객체지향의 단점인 '상태값을 예측하기 힘듦'을 막기위해 외부에서 값을 수정할 수 없게 막아야 합니다.
track.getCarName() 처럼 자동차의 이름만 추출하는 메서드를 만드는 것이 좋아보입니다!

2020-01-27 12:27 UTC, JunHoPark93 commented on src/main/java/controller/Winner.java
> +				.filter(track -> track.getPosition() == max)
아래 것과 마찬가지로 getPosition보다는 max값을 받는 isMatch 라는 boolean을 반환하는 메서드를 사용하는 것이 더 좋습니다!

2020-01-27 12:27 UTC, JunHoPark93 commented on src/main/java/controller/Winner.java
> +public class Winner {
Winner가 컨트롤러 패키지에 들어있습니다. 위치가 여기가 맞을까요?

2020-01-27 12:27 UTC, JunHoPark93 commented on src/main/java/controller/Winner.java
> +	private final static String WINPLAYER = "승리자는 ";
WIN_PLAYER라는 상수명이 마치 우승자의 이름 같습니다. 바꿔보는건 어떨까용

2020-01-27 12:27 UTC, JunHoPark93 commented on src/main/java/controller/Winner.java
> +	public String winner(List<Track> tracks) {
마찬가지로 view (출력) 로직이 들어있습니다. winner를 구하는 메서드는 winner의 리스트만을 반환하고 view 레이어에서 반환받은 리스트로 출력을 그려주는것이 좋습니다.

2020-01-27 12:27 UTC, JunHoPark93 commented on src/main/java/controller/Winner.java
> +		  .collect(Collectors
String.join을 써보는것도 좋을것같아요

2020-01-27 12:27 UTC, JunHoPark93 commented on src/main/java/domain/Car.java
> +	private int randomStep() {
도메인을 더 잘게 분해를 하면 Car는 움직이기 만을 하고 움직일지 말지 결정하는 게임컨트롤러가 하나 더 있다면 테스트하기 쉬울 것 같아요. 그렇게 까지 하기 너무 복잡하다면 이대로 하셔도 좋습니다.
단 MAX 라는 상수명을 SEED (랜덤값 도출에 쓰이므로..) 같은 이름으로 바꾸는 것이 좋아보이네용

2020-01-27 12:27 UTC, JunHoPark93 commented on src/main/java/domain/Car.java
> +		if (state < PAUSE) {
```java
return state < PAUSE ? false : true
```
로 더 간결하게 쓸 수 있을거같아요

2020-01-27 12:27 UTC, JunHoPark93 commented on src/main/java/model/Result.java
> +		try {
쓰레드 sleep을 하신 의도가 있을까요?
그냥 한 번에 결과가 쭈르륵 나와도 괜찮을 것 같아요. 
무언가 exception이 발생했을 때 e.printStackTrace()만 하고 있습니다. catch 블럭에서는 적절한 처리가 있어야합니다.
지금은 그냥 넘어가셔도 좋지만, 나중에 예외처리를 할 때는 항상 catch 블럭에 적절한 행위를 넣어주셔야합니다!

2020-01-27 12:27 UTC, JunHoPark93 commented on src/main/java/model/Result.java
> +	private static final int THREE_SECOND = 3000;
THREE_SECONDS

2020-01-27 12:27 UTC, JunHoPark93 commented on src/main/java/model/Result.java
> +	private static void time() {
sleep을 의도하신거라면 time()이라는 명명 보다는
pause(TRHEE_SECONDS)나 delayPrint(THREE_SECONDS)같이 의도를 더 확실히 드러내는 이름이 더 나을 것 같네요!

2020-01-27 12:27 UTC, JunHoPark93 commented on src/main/java/model/Result.java
> +	private static void threeJump() {
마찬 가지로 출력 로직이네요

2020-01-28 12:07 UTC, asqwklop12 commented on src/main/java/model/Result.java
> +		try {
다른거 쓸려고 했는데 그게 뭔지 까먹어서요... 찾으려 했는데... 깜빡하고 안찾았네요.

2020-01-28 12:18 UTC, asqwklop12 commented
지금 당장 수정할 수 있는 부분들을 수정했습니다. 나머지 부분들도 리뷰해주신 것처럼 진행할 예정입니다. 또한 다음 과제인 로또는 시간이 조금 걸릴 것 같습니다. 왜냐하면 제가 입사를 앞두고 있기 때문에 시간이 될때 하는 것이 좋을 듯 싶습니다. 리뷰 같은 부분은 지금 처럼 늦게 해주셔도 됩니다. 그냥 언젠간 해주시기만 하면 저는 그걸로 만족입니다. 리뷰가 필요할때 다시 리뷰요청 드리겠습니다. ^^감사합니다.

2020-01-28 12:24 UTC, asqwklop12 commented
아, 참고로 저 이거 작성했을때는 이클립스를 사용했습니다. OS는 윈도우입니다. 단축키가 맥이여서... 당황했네요.ㅜㅜ

2022-04-04 12:56 UTC, closed without merging